licenses(["notice"])

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "SyncedQueue",
    hdrs = [
        "synced_queue.h",
    ],
    deps = [
        "@com_google_absl//absl/synchronization",
    ],
)
